# permissions for end users to edit travelbotoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: travelbotoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: travelbot-operator
    app.kubernetes.io/part-of: travelbot-operator
    app.kubernetes.io/managed-by: kustomize
  name: travelbotoperator-editor-role
rules:
- apiGroups:
  - travelbot.ragainsth.com
  resources:
  - travelbotoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - travelbot.ragainsth.com
  resources:
  - travelbotoperators/status
  verbs:
  - get
